<?php
namespace app\index\controller;
use think\Controller;
use think\Session;
use think\Cache;
use think\Request;

class Base extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        define('Admin_ID',Session::get('admin_id'));
//        $admin = Session::get('admin_info');
//        dump(Session::get('admin_info'));die;
        //发送短信
//        smsVerify('13651757624');die;

        $module     = Request::instance()->module(); //模块
        $controller = Request::instance()->controller();//控制器
        $action     = Request::instance()->action(); //方法

        if($controller != 'Admin'){
            $this->alreadyLogin();//防止重复登录
        }

    }

    //判断用户是否登录，放在后台的入口，index/index
    protected function isLogin()
    {
        if(empty(Admin_ID)){
            $this->error('用户未登录，无权访问',url('Admin/login'));
        }
    }

    //防止用户重复登录  Admin/login
    protected function alreadyLogin()
    {
        if(!empty(Admin_ID)){
            //当前session_id
            $sidNow = session_id();
            //缓存的session_id
            $oldSid = Cache::get(Session::get('admin_id'));

            if($oldSid != false){
                if($sidNow != $oldSid){
                    $this->error("您的账号在别的地方登录了，请重新登录！",url('Admin/login'));
                }
            }else{
                Cache::set(Admin_ID,session_id());
            }
        }
    }
}
